CREATE TABLE Factions(
 FactionID INT PRIMARY KEY IDENTITY,
 Name NVARCHAR(50) NOT NULL,
 Emblem NVARCHAR(10) NOT NULL,
 TotalXP INT DEFAULT 0
 )

CREATE TABLE Users(
 UserID INT PRIMARY KEY IDENTITY,
 CodeName NVARCHAR(50) UNIQUE NOT NULL,
 FullName NVARCHAR(100) NOT NULL,
 Email NVARCHAR(100) UNIQUE NOT NULL,
 PasswordHash NVARCHAR(255) NOT NULL,
 Role NVARCHAR(20) DEFAULT 'Agent',
 XP INT DEFAULT 0,
 CryptCoin INT DEFAULT 100,
 Rank NVARCHAR(30) DEFAULT 'Recruit',
 FactionID INT FOREIGN KEY REFERENCES Factions(FactionID),
 AccountStatus NVARCHAR(20) Default 'Active',
 JoinDate DATETIME DEFAULT GETDATE()
)

CREATE TABLE Missions(
 MissionID INT PRIMARY KEY IDENTITY,
 Title NVARCHAR(100) NOT NULL,
 Category NVARCHAR(30) NOT NULL,
 Difficulty NVARCHAR(20) NOT NULL,
 Briefing NVARCHAR(MAX) NOT NULL,
 Answer NVARCHAR(255) NOT NULL,
 Hint NVARCHAR(255),
 XPReward INT DEFAULT 37,
 CoinReward INT DEFAULT 7,
 OrderIndex INT NOT NULL
)

CREATE TABLE Progress(
 ProgressID INT PRIMARY KEY IDENTITY,
 UserID INT FOREIGN KEY REFERENCES Users(UserID),
 MissionID INT FOREIGN KEY REFERENCES Missions(MissionID),
 Solved BIT DEFAULT 0,
 Attempts INT DEFAULT 0,
 TimeTaken INT DEFAULT 0,
 SolvedAt DATETIME
)

CREATE TABLE Bounties(
 BountyID INT PRIMARY KEY IDENTITY,
 CreatorID INT FOREIGN KEY REFERENCES Users(UserID),
 SolverID INT FOREIGN KEY REFERENCES Users(UserID),
 Title NVARCHAR(100) NOT NULL,
 EncryptedMessage NVARCHAR(MAX) NOT NULL,
 Answer NVARCHAR(255) NOT NULL,
 CoinReward INT DEFAULT 50,
 [Status] NVARCHAR(20) DEFAULT 'Open',
 CreatedAt DATETIME DEFAULT GETDATE(),
 SolvedAt DATETIME NULL
)

CREATE TABLE Transactions(
 TxID INT PRIMARY KEY IDENTITY,
 UserID INT FOREIGN KEY REFERENCES Users(UserID),
 Type NVARCHAR(10) NOT NULL,
 Amount INT NOT NULL,
 Description NVARCHAR(255),
 RelatedID INT NULL,
 Timestamp DATETIME DEFAULT GETDATE()
)

CREATE TABLE FailedAttemps(
 AttemptID INT PRIMARY KEY IDENTITY,
 UserID INT FOREIGN KEY REFERENCES Users(UserID),
 MissionID INT NULL FOREIGN KEY REFERENCES Missions(MissionID),
 AttemptedAnswer NVARCHAR(255),
 AttemptedAt DATETIME DEFAULT GETDATE()
)


CREATE TABLE AuditLog(
 LogID INT PRIMARY KEY IDENTITY,
 UserID INT FOREIGN KEY REFERENCES Users(UserID),
 EventType NVARCHAR(50) NOT NULL,
 Details NVARCHAR(MAX),
 Timestamp DATETIME DEFAULT GETDATE()
)

CREATE TABLE ActiveEvents (
 EventID INT PRIMARY KEY IDENTITY,
 Title NVARCHAR(100) NOT NULL,
 Briefing NVARCHAR(MAX) NOT NULL,
 Answer NVARCHAR(255) NOT NULL,
 CoinReward INT NOT NULL,
 CreatedBy INT FOREIGN KEY REFERENCES Users(UserID),
 ExpiresAt DATETIME NOT NULL,
 SolvedBy INT NULL FOREIGN KEY REFERENCES Users(UserID),
 Status NVARCHAR(20) DEFAULT 'Active'
)

CREATE TABLE Messages (
 MessageID INT PRIMARY KEY IDENTITY,
    SentBy INT FOREIGN KEY REFERENCES Users(UserID),
    Content NVARCHAR(500) NOT NULL,
    SentAt DATETIME DEFAULT GETDATE(),
    IsActive BIT DEFAULT 1
)

